function [fitresult, gof] = createFit(x1, x2, y)
%CREATEFIT1(X1,X2,Y)
%  Create a fit.
%
%  Data for 'fit_test' fit:
%      X Input : x1
%      Y Input : x2
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2017 19:37:21


%% Fit: 'fit_test'.
[xData, yData, zData] = prepareSurfaceData( x1, x2, y );

% Set up fittype and options.
ft = fittype( 'b0 + b1*x + b2*y + b12*x*y', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.915991244131425 0.00115105712910724 0.424349039815375 0.460916366028964];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit_test' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'fit_test', 'y vs. x1, x2', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel x2
zlabel y
grid on


