function [fitresult, gof] = createFit_RSM(x1, x2, y)
%CREATEFIT1(X1,X2,Y)
%  Create a fit.
%
%  Data for 'fit_test_RSM' fit:
%      X Input : x1
%      Y Input : x2
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2017 19:27:13


%% Fit: 'fit_test_RSM'.
[xData, yData, zData] = prepareSurfaceData( x1, x2, y );

% Set up fittype and options.
ft = fittype( 'b0 + b1*x + b2*y + b12*x*y  + b11*x^2 + b22*y^2', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.669175304534394 0.190433267179954 0.368916546063895 0.460725937260412 0.98163795097075 0.156404952226563];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit_test_RSM' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'fit_test_RSM', 'y vs. x1, x2', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel x2
zlabel y
grid on


