function [fitresult, gof] = createFit_LOESS(x1, x2, y)
%CREATEFIT1(X1,X2,Y)
%  Create a fit.
%
%  Data for 'LOESS_fit' fit:
%      X Input : x1
%      Y Input : x2
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Apr-2017 12:26:26


%% Fit: 'LOESS_fit'.
[xData, yData, zData] = prepareSurfaceData( x1, x2, y );

% Set up fittype and options.
ft = fittype( 'loess' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'LOESS_fit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'LOESS_fit', 'y vs. x1, x2', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel x2
zlabel y
grid on
view( -52.3, 10.8 );


